// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteSave(arg1) {
  return window['go']['main']['SaveManager']['DeleteSave'](arg1);
}

export function GetAllSaves() {
  return window['go']['main']['SaveManager']['GetAllSaves']();
}

export function GetLastSave() {
  return window['go']['main']['SaveManager']['GetLastSave']();
}

export function LoadGame(arg1) {
  return window['go']['main']['SaveManager']['LoadGame'](arg1);
}

export function SaveGame(arg1, arg2) {
  return window['go']['main']['SaveManager']['SaveGame'](arg1, arg2);
}

export function SetLastSave(arg1) {
  return window['go']['main']['SaveManager']['SetLastSave'](arg1);
}
