// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteSave(arg1:string):Promise<void>;

export function GetAllSaves():Promise<Array<string>>;

export function GetLastSave():Promise<string>;

export function LoadGame(arg1:string):Promise<string>;

export function SaveGame(arg1:string,arg2:string):Promise<void>;

export function SetLastSave(arg1:string):Promise<void>;
